"""Request types for Notion API.

このモジュールは、Notion APIへのリクエストに使用する型定義を提供します。
主にPage作成・更新時のプロパティ値の設定に使用します。
"""

from .common import (
    AnnotationRequest,
    AfterBlockPositionRequest,
    BlockIdReferenceRequest,
    DateRequest,
    DefaultPageTemplateRequest,
    GroupObjectRequest,
    IdRequest,
    PageIconRequest,
    PageCoverRequest,
    PageEndPositionRequest,
    PagePositionRequest,
    PageStartPositionRequest,
    PageTemplateRequest,
    InternalFileRequest,
    ExternalFileRequest,
    InternalOrExternalFileWithNameRequest,
    FileUploadIdRequest,
    FileUploadWithOptionalNameRequest,
    PartialUserObjectRequest,
    RelationItemRequest,
    SelectPropertyItemRequest,
    TemplateIdPageTemplateRequest,
)
from .page_requests import (
    CreatePageParameters,
    InsertContentMarkdownCommand,
    InsertContentMarkdownRequest,
    MarkdownContentUpdateRequest,
    PageMarkdownCommand,
    ReplaceContentMarkdownCommand,
    ReplaceContentMarkdownRequest,
    ReplaceContentRangeMarkdownCommand,
    ReplaceContentRangeMarkdownRequest,
    UpdateContentMarkdownCommand,
    UpdateContentMarkdownRequest,
    UpdatePageParameters,
)
from .property_requests import (
    CheckboxPropertyRequest,
    DatePropertyRequest,
    EmailPropertyRequest,
    FilesPropertyRequest,
    MultiSelectPropertyRequest,
    NumberPropertyRequest,
    PeoplePropertyRequest,
    PhoneNumberPropertyRequest,
    PropertyRequest,
    RelationPropertyRequest,
    RichTextPropertyRequest,
    SelectPropertyRequest,
    StatusPropertyRequest,
    TitlePropertyRequest,
    UrlPropertyRequest,
    VerificationPropertyRequest,
    VerificationStateDateRequest,
    VerificationValueRequest,
)

__all__ = [
    # Page requests
    "CreatePageParameters",
    "UpdatePageParameters",
    "PageMarkdownCommand",
    "MarkdownContentUpdateRequest",
    "UpdateContentMarkdownRequest",
    "UpdateContentMarkdownCommand",
    "ReplaceContentMarkdownRequest",
    "ReplaceContentMarkdownCommand",
    "InsertContentMarkdownRequest",
    "InsertContentMarkdownCommand",
    "ReplaceContentRangeMarkdownRequest",
    "ReplaceContentRangeMarkdownCommand",
    # Property requests
    "PropertyRequest",
    "TitlePropertyRequest",
    "RichTextPropertyRequest",
    "NumberPropertyRequest",
    "UrlPropertyRequest",
    "SelectPropertyRequest",
    "MultiSelectPropertyRequest",
    "PeoplePropertyRequest",
    "EmailPropertyRequest",
    "PhoneNumberPropertyRequest",
    "DatePropertyRequest",
    "CheckboxPropertyRequest",
    "RelationPropertyRequest",
    "FilesPropertyRequest",
    "StatusPropertyRequest",
    "VerificationPropertyRequest",
    "VerificationValueRequest",
    "VerificationStateDateRequest",
    # Common types
    "IdRequest",
    "DateRequest",
    "AnnotationRequest",
    "PartialUserObjectRequest",
    "GroupObjectRequest",
    "RelationItemRequest",
    "SelectPropertyItemRequest",
    "BlockIdReferenceRequest",
    # Files and icon/cover request helpers
    "InternalFileRequest",
    "ExternalFileRequest",
    "InternalOrExternalFileWithNameRequest",
    "FileUploadIdRequest",
    "FileUploadWithOptionalNameRequest",
    "PageIconRequest",
    "PageCoverRequest",
    "PageTemplateRequest",
    "DefaultPageTemplateRequest",
    "TemplateIdPageTemplateRequest",
    "PagePositionRequest",
    "PageStartPositionRequest",
    "PageEndPositionRequest",
    "AfterBlockPositionRequest",
]
